'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from '@/context/AuthContext'
import Link from 'next/link';
import Image from 'next/image';
import { useAuthContext } from "@/context/AuthContext";
import Navbar from "./navbar";

/*const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/


export default function RootLayout({ children }) {

  const { user } = useAuthContext()
  return (
    <html lang="en">
      <body /*className={inter.className}*/>
      <AuthContextProvider>
          <Navbar/>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
